### ISSUE TITLE
Ensuring images directory isn't working for pretext build html

### ISSUE THREAD

**Issue by StevenClontz** [StevenClontz/pretext.py#3]
For whatever reason, despite https://github.com/StevenClontz/pretext.py/commit/e82a710b50b5a5f53b697a79e5551c5953e2f1fd#diff-4c6d54544e27bbf145850658400c090eR16 I'm getting this error:

```
user@project-0b735a53-2e2b-4036-8489-d78a5a2e237c ~/mathematics-of-data (master)
[pipenv]$ pretext build html
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/pretext.py-R-1-40qH/bin/pretext", line 11, in <module>
    load_entry_point('pretext', 'console_scripts', 'pretext')()
  File "/home/user/.local/share/virtualenvs/pretext.py-R-1-40qH/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/share/virtualenvs/pretext.py-R-1-40qH/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/share/virtualenvs/pretext.py-R-1-40qH/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/share/virtualenvs/pretext.py-R-1-40qH/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/share/virtualenvs/pretext.py-R-1-40qH/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/pretext.py/pretext/cli.py", line 75, in build
    build.html(input,output,stringparams)
  File "/home/user/pretext.py/pretext/build.py", line 20, in html
    src_files = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/mathematics-of-data/source/images'
```

**Comment by oscarlevin** [comment]
Fixed now, at 2503fef.  But there is a larger issue about images which I will post as a new issue.
